function getMoviesData(){
    return [
      {title: 'Black Mirror', id: 'blackMirror', synopsis: 'An anthology series exploring a twisted, high-tech world where humanity\'s greatest innovations and darkest instincts collide.'},
      {title: 'Breaking Bad', id: 'breakingBad', synopsis: 'A high school chemistry teacher diagnosed with inoperable lung cancer turns to manufacturing and selling methamphetamine in order to secure his family\'s future.'},
      {title: 'Death Note', id: 'deathNote', synopsis: 'A high school student named Light Turner discovers a mysterious notebook that has the power to kill anyone whose name is written within its pages, and launches a secret crusade to rid the world of criminals.'},
      {title: 'Game of Thrones', id: 'gameOfThrones', synopsis: 'Nine noble families fight for control over the mythical lands of Westeros, while an ancient enemy returns after being dormant for thousands of years.'},
      {title: 'The Walking Dead', id: 'theWalkingDead', synopsis: 'Sheriff Deputy Rick Grimes wakes up from a coma to learn the world is in ruins and infested by zombies. He must lead a group of survivors to stay alive.'},
      {title: 'Iron Man 2', id: 'ironMan2', synopsis: 'With the world now aware of his identity as Iron Man, Tony Stark must contend with both his declining health and a vengeful mad man with ties to his father\'s legacy.'},
      {title: 'Spider Man Homecoming', id: 'spidermanHomecoming', synopsis: 'Peter Parker balances his life as an ordinary high school student in Queens with his superhero alter-ego Spider-Man, and finds himself on the trail of a new menace prowling the skies of New York City.'},
      {title: 'Black Panther', id: 'blackPanther', synopsis: 'T\'Challa, heir to the hidden but advanced kingdom of Wakanda, must step forward to lead his people into a new future and must confront a challenger from his country\'s past.'},
      {title: 'Justice League', id: 'justiceLeague', synopsis: 'Fueled by his restored faith in humanity and inspired by Superman\'s selfless act, Bruce Wayne enlists the help of his newfound ally, Diana Prince, to face an even greater enemy. Together, Batman and Wonder Woman work quickly to find and recruit a team of meta-humans to stand against this newly awakened threat.'},
      {title: 'COCO', id: 'coco', synopsis: 'Despite his family\'s baffling generations-old ban on music, Miguel dreams of becoming an accomplished musician like his idol, Ernesto de la Cruz. Desperate to prove his talent, Miguel finds himself in the stunning and colorful Land of the Dead following a mysterious chain of events. Along the way, he meets charming trickster Hector, and together, they set off on an extraordinary journey to unlock the real story behind Miguel\'s family history.'},
      {title: 'The Gentlemen', id: 'theGentlemen', synopsis: 'A talented American graduate of Oxford, using his unique skills, and audacity, creates a marijuana empire using the estates of impoverished British aristocrats. However, when he tries to sell his empire to a fellow American billionaire, a chain of events unfolds, involving blackmail, deception, mayhem and murder between street thugs, Russian oligarchs, Triad gangsters and gutter journalists.'},
      {title: 'The Lion King', id: 'theLionKing', synopsis: 'A young lion prince is cast out of his pride by his cruel uncle, who claims he killed his father. While the uncle rules with an iron paw, the prince grows up beyond the Savannah, living by a philosophy: No worries for the rest of your days. But when his past comes to haunt him, the young prince must decide his fate: Will he remain an outcast or face his demons and become what he needs to be?'},
      {title: 'Avengers: ENDGAME', id: 'avengersEndgame', synopsis: 'After the devastating events of Avengers: Infinity War (2018), the universe is in ruins. With the help of remaining allies, the Avengers assemble once more in order to reverse Thanos\' actions and restore balance to the universe.'},
      {title: 'JOKER', id: 'joker', synopsis: 'Arthur Fleck works as a clown and is an aspiring stand-up comic. He has mental health issues, part of which involves uncontrollable laughter. Times are tough and, due to his issues and occupation, Arthur has an even worse time than most. Over time these issues bear down on him, shaping his actions, making him ultimately take on the persona he is more known as Joker.'},
      {title: 'IT: Chapter Two', id: 'itChapterTwo', synopsis: 'Derry, Maine. A small town with a terrible curse. Every 27 years, an ancient being comes up from the sewer depths to feed off of the fear of children. Since it\'s defeat in 1989, Pennywise has grown hungry, and is now back with a vengeance. If the losers club doesn\'t defeat him this time, their worst fear will become a reality, with nothing to stop him. The clock is ticking. Who\'s going to be scared first?'},
      {title: 'Dunkirk', id: 'dunkirk', synopsis: 'May/June 1940. Four hundred thousand British and French soldiers are hole up in the French port town of Dunkirk. The only way out is via sea, and the Germans have air superiority, bombing the British soldiers and ships without much opposition. The situation looks dire and, in desperation, Britain sends civilian boats in addition to its hard-pressed Navy to try to evacuate the beleaguered forces. This is that story, seen through the eyes of a soldier amongst those trapped forces, two Royal Air Force fighter pilots, and a group of civilians on their boat, part of the evacuation fleet.'},
      {title: 'Logan', id: 'logan', synopsis: 'In the not-so-distant 2029, the entire mutant race is almost obliterated, and Logan, the invincible bestial superhero once known as the Wolverine, finds himself getting old, and his incredible healing ability significantly weakened. As an incognito limo driver, Logan does his best to guard and keep out of sight a weary nonagenarian Professor Xavier; however, things will take an unexpected turn when a cryptic woman asks him to transport the young mutant girl, Laura. A better future lies past the Canadian borders for the unaccompanied teenager, but the government is unwilling to let go of its asset so easily. In the end, can the ageing Logan protect both himself and Laura?'},
      {title: 'Spider-Man: Into the Spider-verse', id: 'spidermanIntoTheSpiderverse', synopsis: 'Phil Lord and Christopher Miller, the creative minds behind The Lego Movie and 21 Jump Street, bring their unique talents to a fresh vision of a different Spider-Man Universe, with a groundbreaking visual style that\'s the first of its kind. "Spider-Man(TM): Into the Spider-Verse" introduces Brooklyn teen Miles Morales (Shameik Moore), and the limitless possibilities of the Spider-Verse, where more than one can wear the mask.'},
      {title: 'John Wick', id: 'johnWick', synopsis: 'An ex-hit-man comes out of retirement to track down the gangsters that killed his dog and took everything from him.'},
      {title: 'Once upon a time in... Hollywood', id: 'onceUponATimeInHollywood', synopsis: 'Quentin Tarantino\'s Once Upon a Time... in Hollywood visits 1969 Los Angeles, where everything is changing, as TV star Rick Dalton (Leonardo DiCaprio) and his longtime stunt double Cliff Booth (Brad Pitt) make their way around an industry they hardly recognize anymore. The ninth film from the writer-director features a large ensemble cast and multiple storylines in a tribute to the final moments of Hollywood\'s golden age.'},
    ];
  }

module.exports = getMoviesData();